const WALL_SENSE_TYPES = {
    NONE: 0,
    LIMITED: 10,
    NORMAL: 20
}
const WALL_DIRECTIONS = {
    BOTH: 0,
    LEFT: 1,
    RIGHT: 2
}
const WALL_DOOR_TYPES = {
    NONE: 0,
    DOOR: 1,
    SECRET: 2
}
const WALL_DOOR_STATES = {
    CLOSED: 0,
    OPEN: 1,
    LOCKED: 2
}
const WALL_COVER_TYPES = {
    HALF: '1/2',
    THREE_QUARTERS: '3/4',
    FULL: '1/1'
}
const TERRAIN_CLASSIFICATIONS = {
    NORMAL: 0,
    DIFFICULT: 1,
    COVER: 2,
}
const DIRECTIONS = {
    VERTICAL_TOP_LEFT_TO_BOTTOM_RIGHT: 1,
    HORIZONTAL_TOP_LEFT_TO_BOTTOM_RIGHT: 2,
    VERTICAL_BOTTOM_RIGHT_TO_TOP_LEFT: 3,
    HORIZONTAL_BOTTOM_RIGHT_TO_TOP_LEFT: 4,
}
const IMAGE_SIZE_MODIFIER = 0.85
const HILL_SIZE = 2.5
const CLIFF_SIZE = 10